### ISSUE TITLE
Clarify whether this can be used for receiving input (and how)

### ISSUE THREAD

**Issue by skorokithakis** [jcheger/arduino-frskysp#1]
I'm sorry for the ignorant question, but I didn't see anything in the repo: This library seems like it can be used to read SBUS compatible sensors, but can I use it with my receiver to remote-control my builds?

For example, if I make a controller for some servos, can I connect my receiver over SBUS to the Arduino and use my FrSKY RC to control the servos? I.e., can I use this library to read inputs from my radio's gimbals/switches/etc?

If yes, can an example be added? If not, maybe that can be more explicit in the README, perhaps with a link to some other library that does do this?

**Comment by Septeract7** [comment]
Hi
I am on a very similar project. I am writing some code for arduino to receive stick commands, switch positions etc from a Taranis QX7 and sending them to a diy quadcopter via an nrf24l01 module. 
For doing this you don't need to receive data from the SmartPort but from the PPM pin in the module bay in your Taranis. You may want to have a look at the project from which I have taken the PPM decoder code and schematics. You can find the code [here](https://github.com/goebish/nrf24_multipro) and the schematics [here](https://github.com/mozgy/nRF24-MultiPro). 
You could use the SmartPort for sending Telemetry data to the Taranis and displaying it there. 

A thing I am not sure about, is if the SmartPort in the module bay is 5V tolerant or if I destroy something by wiring an Arduino Nano directly to the Taranis...
